# Generated by Django 2.2 on 2021-04-18 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210417_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='duration',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
