# Generated by Django 2.2 on 2021-04-19 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210418_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='track_id',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
